#!/bin/bash

rm -rf .git .tmux .vim .config/bat .config/git
mv -f {dotfiles/*,dotfiles/.*} ~/
rm -r dotfiles
~/.vim/installvim

mkdir -p ~/.tmux/themes
cd ~/.tmux/themes
git clone https://github.com/arcticicestudio/nord-tmux
cd $HOME
