#!/bin/bash

cd $HOME
rm -rf .gf .git .tmux .vim .config/bat .config/git
mv -f {dotfiles/*,dotfiles/.*} $HOME/
mkdir -p $HOME/.config
mkdir -p $HOME/{bin,.local/bin,.local/share}
mkdir -p $HOME/.ssh
chmod 700 $HOME
chmod 700 $HOME/{.config,.local/share,.ssh}
chmod 755 $HOME/{bin,.local/bin}
mv dotfiles/.config/{bat,git} $HOME/.config/
rm -r dotfiles
$HOME/.vim/installvim

mkdir -p $HOME/.tmux/themes
cd $HOME/.tmux/themes
git clone https://github.com/arcticicestudio/nord-tmux
cd $HOME
