#!/bin/sh

sudo apt-get update
sudo apt-get --no-install-recommends install vim-nox -y
sudo apt-get install git -y
#sudo apt-get --no-install-recommends install vim-nox fonts-firacode -y #gui
sudo update-alternatives --set editor /usr/bin/vim.nox
sudo update-alternatives --set ex /usr/bin/vim.nox
sudo update-alternatives --set rview /usr/bin/vim.nox
sudo update-alternatives --set rvim /usr/bin/vim.nox
sudo update-alternatives --set vi /usr/bin/vim.nox
sudo update-alternatives --set view /usr/bin/vim.nox
sudo update-alternatives --set vim /usr/bin/vim.nox
sudo update-alternatives --set vimdiff /usr/bin/vim.nox
mkdir -p ~/.vim/pack/mdr/start
cd ~/.vim/pack/mdr/start
git clone https://github.com/tpope/vim-sensible
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/editorconfig/editorconfig-vim
git clone https://github.com/sonph/onehalf
mv onehalf/vim vim-onehalf
rm -rf onehalf
cd ~
