set background=dark
syntax on
set t_Co=256
"set cursorline
let g:airline_theme='onehalfdark'
let g:airline_powerline_fonts=1

set colorcolumn=80

au BufNewFile,BufRead *.py
 \ set tabstop=4
 \| set softtabstop=4
 \| set shiftwidth=4
 \| set expandtab
 \| set autoindent

au BufNewFile,BufRead *.js, *.html, *.css
 \ set tabstop=2
 \| set softtabstop=2
 \| set shiftwidth=2
